/*
 * Copyright 2019 Skullabs Contributors (https://github.com/skullabs)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package kos.core.client.sample;

import io.vertx.core.Future;
import io.vertx.core.http.HttpMethod;
import kos.api.KosConfiguration;
import kos.api.MutableKosConfiguration;
import kos.core.client.AutoGeneratedRestClient;
import kos.core.client.RestClientConfiguration;

public class WhatsMyIpClient extends AutoGeneratedRestClient {
    
    private static final KosConfiguration kosConf = new MutableKosConfiguration();
    private static final RestClientConfiguration restConf = RestClientConfiguration.withUrl("https://api.ipify.org")
        .build().useDefaultsForNullProperties(kosConf);

    public WhatsMyIpClient() {
        super(restConf);
    }

    public Future<MyIpResponse> myIp(){
        return execute(
            HttpMethod.GET, "?format=json",
            createEmptyHeaders(), MyIpResponse.class
        );
    }
}
